name: Package.json Compatibility Check

on:
    push:
        branches: [ "main", "master" ]
    pull_request:
        branches: [ "main", "master" ]

jobs:
    module-name-check:
        name: Module Name & Path Name Verification
        runs-on: ubuntu-latest

        steps:
          - name: Confirm Package.json
            if: ${{hashFiles('package.json') != ''}}
            run: echo "Package.json exist."

        #   - name: Validate displayName via Python
        #     shell: bash
        #     run: |
        #         python3 -c '
        #         import json, sys

        #         try:
        #             with open("package.json", "r", encoding="utf-8") as f:
        #                 data = json.load(f)
        #         except Exception as e:
        #             print(f"::error::package.json okunamadı veya JSON formatı geçersiz: {e}")
        #             sys.exit(1)

        #         display_name = data.get("displayName")

        #         if not display_name:
        #             print("::error::package.json içinde \"displayName\" alanı bulunamadı!")
        #             sys.exit(1)

        #         if not display_name.endswith("Module"):
        #             print(f"::error::\"displayName\" değeri \"Module\" ile bitmelidir! Mevcut değer: \"{display_name}\"")
        #             sys.exit(1)

        #         print(f"::notice::displayName doğrulandı: \"{display_name}\"")
        #         '
    